{{
    config(
        tags=['mart']
    )
}}

WITH

STG_TIMESHEETS AS (
    SELECT * FROM {{ ref('stg_timesheets') }}
),

DATE_START_FOR_PROJECT AS (
    SELECT 
        T.PROJECT_SELECTED AS PROJECT_SELECTED,
        FIRST_DATE_STARTS_FOR_PROJECTS.DATE_START AS DATE_START
    FROM 
        STG_TIMESHEETS T,
        (
            SELECT * 
            FROM (
                SELECT 
                    *,
                    ROW_NUMBER() OVER(PARTITION BY PROJECT_SELECTED
                        ORDER BY TO_DATE(DATE_START, 'DD-MM-YYYY')) AS RANK
                FROM STG_TIMESHEETS
            )
            WHERE RANK = 1
        ) AS FIRST_DATE_STARTS_FOR_PROJECTS
    WHERE
        FIRST_DATE_STARTS_FOR_PROJECTS.PROJECT_SELECTED = T.PROJECT_SELECTED
    GROUP BY
        T.PROJECT_SELECTED,
        FIRST_DATE_STARTS_FOR_PROJECTS.DATE_START
),

DATE_END_FOR_PROJECT AS (
    SELECT 
        T.PROJECT_SELECTED AS PROJECT_SELECTED,
        FIRST_DATE_ENDS_FOR_PROJECTS.DATE_END AS DATE_END
    FROM 
        STG_TIMESHEETS T,
        (
            SELECT * 
            FROM (
                SELECT 
                    *,
                    ROW_NUMBER() OVER(PARTITION BY PROJECT_SELECTED
                        ORDER BY TO_DATE(DATE_END, 'DD-MM-YYYY') DESC) AS RANK
                FROM STG_TIMESHEETS
            )
            WHERE RANK = 1
        ) AS FIRST_DATE_ENDS_FOR_PROJECTS
    WHERE
        FIRST_DATE_ENDS_FOR_PROJECTS.PROJECT_SELECTED = T.PROJECT_SELECTED
    GROUP BY
        T.PROJECT_SELECTED,
        FIRST_DATE_ENDS_FOR_PROJECTS.DATE_END
),

COUNT_WEEKS_FOR_PROJECT AS (
    SELECT 
        PROJECT_SELECTED,
        COUNT(DATE_START) AS COUNT_WEEKS
    FROM
        (
            SELECT 
                PROJECT_SELECTED,
                DATE_START,
            FROM 
                STG_TIMESHEETS
            GROUP BY
                PROJECT_SELECTED,
                DATE_START
        )
    GROUP BY
        PROJECT_SELECTED
),

FIND_DAY_SPANS AS (
    SELECT 
        T.PROJECT_SELECTED, 
        DS.DATE_START,
        DE.DATE_END,
        (TO_DATE(DE.DATE_END, 'DD-MM-YYYY') - TO_DATE(DS.DATE_START, 'DD-MM-YYYY')) AS TOTAL_DAYS_SPAN,
        CW.COUNT_WEEKS * 7 AS TOTAL_DAYS_WORKED_FOR,
        (TOTAL_DAYS_SPAN - TOTAL_DAYS_WORKED_FOR) AS DAYS_GAPS,
    FROM 
        DATE_START_FOR_PROJECT DS,
        DATE_END_FOR_PROJECT DE,
        STG_TIMESHEETS T,
        COUNT_WEEKS_FOR_PROJECT CW
    WHERE 
        T.PROJECT_SELECTED = DS.PROJECT_SELECTED
        AND
        T.PROJECT_SELECTED = DE.PROJECT_SELECTED
        AND
        T.PROJECT_SELECTED = CW.PROJECT_SELECTED
    GROUP BY
        T.PROJECT_SELECTED, 
        DS.DATE_START,
        DE.DATE_END,
        CW.COUNT_WEEKS
),

MIN_AND_MAX_DAY_GAPS AS (
    SELECT 
        MIN(DAYS_GAPS) AS MIN_DAYS_GAPS,
        MAX(DAYS_GAPS) AS MAX_DAYS_GAPS
    FROM FIND_DAY_SPANS
),

FINDING_EFFICIENCY AS (
    SELECT 
        FIND_DAY_SPANS.*,
        (1 - ((DAYS_GAPS - MIN_DAYS_GAPS) / MAX_DAYS_GAPS)) * 100 AS EFFICIENCY
    FROM 
        FIND_DAY_SPANS,
        MIN_AND_MAX_DAY_GAPS
)

SELECT * FROM FINDING_EFFICIENCY