version: 2

sources:
    - name: raw_src
      database: JMAN_FINAL_PROJECT
      schema: dbo
      tables:
          - name: users
          - name: timesheets
          - name: projectstousers
          - name: projectstofeedbackquestions
          - name: projects
          - name: feedbackquestions
          - name: feedbackanswers
