{{
    config(
        tags=['basic', 'staging']
    )
}}

WITH

RAW_DATA AS (
    SELECT * FROM {{ source('raw_src', 'feedbackanswers') }}
),

CAST_DATA AS (
    SELECT 
        CAST(PROJECTNAME AS VARCHAR) AS PROJECT_NAME,
        CAST(FEEDBACKQUESTIONNAME AS VARCHAR) AS FEEDBACKQUESTION_NAME,
        CAST(DATESTART AS VARCHAR) AS DATE_START,
        CAST(DATEEND AS VARCHAR) AS DATE_END,
        CAST(USEREMAIL AS VARCHAR) AS USER_EMAIL,
        CAST(CHECKEDANSWER AS NUMBER) AS CHECKED_ANSWER,
        CAST(TEXTANSWER AS VARCHAR) AS TEXT_ANSWER,
    FROM 
        RAW_DATA
),

REMOVE_NULLS AS (
    SELECT 
        PROJECT_NAME, FEEDBACKQUESTION_NAME, DATE_START, DATE_END, USER_EMAIL,
        CASE
            WHEN CHECKED_ANSWER IS NULL
            THEN 0
            ELSE CHECKED_ANSWER 
        END AS CHECKED_ANSWER,

        CASE
            WHEN TEXT_ANSWER IS NULL
            THEN ''
            ELSE TEXT_ANSWER 
        END AS TEXT_ANSWER,

    FROM CAST_DATA
)

SELECT * FROM REMOVE_NULLS