{{
    config(
        tags=['basic', 'staging']
    )
}}

WITH

FEEDBACKANSWERS AS (
    SELECT * FROM {{ source('raw_src', 'feedbackanswers') }}
),

FEEDBACKANSWERS2 AS (
    SELECT 
        PROJECTNAME, FEEDBACKQUESTIONNAME,
        CASE
            WHEN CHECKEDANSWER IS NULL
            THEN 0
            ELSE CHECKEDANSWER 
        END AS CHECKEDANSWER,

        CASE
            WHEN TEXTANSWER IS NULL
            THEN ''
            ELSE TEXTANSWER 
        END AS TEXTANSWER,

        DATESTART, DATEEND, USEREMAIL
    FROM FEEDBACKANSWERS
),

STG_FEEDBACKANSWERS AS (
    SELECT 
        CAST(PROJECTNAME AS VARCHAR) AS PROJECT_NAME,
        CAST(FEEDBACKQUESTIONNAME AS VARCHAR) AS FEEDBACKQUESTION_NAME,
        CAST(CHECKEDANSWER AS NUMBER) AS CHECKED_ANSWER,
        CAST(TEXTANSWER AS VARCHAR) AS TEXT_ANSWER,
        CAST(DATESTART AS VARCHAR) AS DATE_START,
        CAST(DATEEND AS VARCHAR) AS DATE_END,
        CAST(USEREMAIL AS VARCHAR) AS USER_EMAIL
    FROM 
        FEEDBACKANSWERS2
)

SELECT * FROM STG_FEEDBACKANSWERS