SELECT 
    STG_TIMESHEETS.USER_EMAIL AS USER_EMAIL,
    STG_USERS.ROLE AS USER_ROLE,
    STG_TIMESHEETS.PROJECT_SELECTED AS PROJECT_NAME,
    STG_PROJECTS.DOMAIN AS PROJECT_DOMAIN,
    STG_TIMESHEETS.DATE_START AS DATE_START,
    STG_TIMESHEETS.DATE_END AS DATE_END,
    STG_TIMESHEETS.COMMENT_ADDED AS TIMESHEET_COMMENT_ADDED,
    STG_TIMESHEETS.D0 AS TIMESHEET_D0,
    STG_TIMESHEETS.D1 AS TIMESHEET_D1,
    STG_TIMESHEETS.D2 AS TIMESHEET_D2,
    STG_TIMESHEETS.D3 AS TIMESHEET_D3,
    STG_TIMESHEETS.D4 AS TIMESHEET_D4,
    STG_TIMESHEETS.D5 AS TIMESHEET_D5,
    STG_TIMESHEETS.D6 AS TIMESHEET_D6,
    STG_TIMESHEETS.ACTIVITY_NAME AS TIMESHEET_ACTIVITY_NAME,
    STG_FEEDBACKANSWERS.FEEDBACKQUESTION_NAME AS FEEDBACK_QUESTION,
    STG_FEEDBACKANSWERS.CHECKED_ANSWER AS FEEDBACK_CHECKED_ANSWER,
    STG_FEEDBACKANSWERS.TEXT_ANSWER AS FEEDBACK_TEXT_ANSWER

FROM
    (STG_TIMESHEETS
    FULL OUTER JOIN 
    STG_FEEDBACKANSWERS     ON  STG_TIMESHEETS.USER_EMAIL = STG_FEEDBACKANSWERS.USER_EMAIL
                                AND
                                STG_TIMESHEETS.PROJECT_SELECTED = STG_FEEDBACKANSWERS.PROJECT_NAME
                                AND
                                STG_TIMESHEETS.DATE_START = STG_FEEDBACKANSWERS.DATE_START)
    ,
    STG_USERS,
    STG_PROJECTS,
    STG_PROJECTSTOUSERS,

WHERE
    STG_USERS.EMAIL = STG_PROJECTSTOUSERS.USER_EMAIL
    AND
    STG_PROJECTSTOUSERS.PROJECT_NAME = STG_TIMESHEETS.PROJECT_SELECTED
    AND
    STG_PROJECTS.NAME = STG_TIMESHEETS.PROJECT_SELECTED
    AND
    STG_TIMESHEETS.USER_EMAIL = STG_USERS.EMAIL