SELECT 
    STG_USERS.EMAIL AS USER_EMAIL,
    STG_USERS.ROLE AS USER_ROLE,
    STG_USERS.NAME AS USER_NAME,
    STG_PROJECTS.NAME AS PROJECT_NAME,
    STG_PROJECTS.DOMAIN AS PROJECT_DOMAIN,
    STG_FEEDBACKQUESTIONS.QUESTION AS FEEDBACK_QUESTION,
    STG_TIMESHEETS.DATE_START AS PROJECT_DATE_START,
    STG_TIMESHEETS.DATE_END AS PROJECT_END_DATE,
    STG_TIMESHEETS.COMMENT_ADDED AS TIMESHEET_COMMENT_ADDED,
    STG_TIMESHEETS.D0 AS TIMESHEET_D0,
    STG_TIMESHEETS.D1 AS TIMESHEET_D1,
    STG_TIMESHEETS.D2 AS TIMESHEET_D2,
    STG_TIMESHEETS.D3 AS TIMESHEET_D3,
    STG_TIMESHEETS.D4 AS TIMESHEET_D4,
    STG_TIMESHEETS.D5 AS TIMESHEET_D5,
    STG_TIMESHEETS.D6 AS TIMESHEET_D6,
    STG_TIMESHEETS.ACTIVITY_NAME AS TIMESHEET_ACTIVITY_NAME,
    STG_FEEDBACKANSWERS.DATE_START AS FEEDBACK_DATE_START,
    STG_FEEDBACKANSWERS.DATE_END AS FEEDBACK_DATE_END,
    STG_FEEDBACKANSWERS.CHECKED_ANSWER AS FEEDBACK_CHECKED_ANSWER,
    STG_FEEDBACKANSWERS.TEXT_ANSWER AS FEEDBACK_TEXT_ANSWER

FROM 
    STG_USERS,
    STG_PROJECTS,
    STG_FEEDBACKQUESTIONS,
    STG_PROJECTSTOUSERS,
    STG_PROJECTSTOFEEDBACKQUESTIONS,
    STG_TIMESHEETS,
    STG_FEEDBACKANSWERS

WHERE
    STG_USERS.EMAIL = STG_PROJECTSTOUSERS.USER_EMAIL
    AND
    STG_PROJECTSTOUSERS.PROJECT_NAME = STG_PROJECTS.NAME
    AND
    STG_PROJECTS.NAME = STG_PROJECTSTOFEEDBACKQUESTIONS.PROJECT_NAME
    AND
    STG_PROJECTSTOFEEDBACKQUESTIONS.QUESTION_NAME = STG_FEEDBACKQUESTIONS.QUESTION
    AND
    STG_TIMESHEETS.USER_EMAIL = STG_USERS.EMAIL
    AND
    STG_TIMESHEETS.PROJECT_SELECTED = STG_PROJECTS.NAME
    AND
    STG_FEEDBACKANSWERS.PROJECT_NAME = STG_PROJECTS.NAME
    AND
    STG_FEEDBACKANSWERS.FEEDBACKQUESTION_NAME = STG_FEEDBACKQUESTIONS.QUESTION
    AND
    STG_FEEDBACKANSWERS.USER_EMAIL = STG_USERS.EMAIL